name: fbsd test
# on: [push]
# on:
#   release:
#     types: [published]
on: [workflow_dispatch]
# TODO:
# - Can we check out first, bootstrap and then cache/upload/download into container?
# - Build for sunOS?
# - Cache / Speedup VM builds (OpenBSD, FreeBSD, macOS)

permissions:
  contents: write

env:
  OPENSSL_VER: 3.0.11
  VER: 1.4.41

jobs:
  # Create release Tarballs
  BSD:
    strategy:
      matrix:
          os: [freebsd]  
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Starting the VM
        uses: vmactions/freebsd-vm@v0
        with:
          release: 12.3
          usesh: true
          prepare: |
            pkg install -y curl automake autoconf gcc

          run: |
            pkg search opencrypto
            id
            uname -a
            curl -SsfL https://www.openssl.org/source/openssl-${OPENSSL_VER:-1.1.1k}.tar.gz | tar -xzf - -C /tmp/
            ( cd /tmp/openssl-${OPENSSL_VER:-1.1.1k} && \
            ./Configure --prefix=/opt no-tests no-dso no-threads no-shared BSD-generic64 && \
            make install_sw )
            rm -rf rm -rf /tmp/openssl-${OPENSSL_VER:-1.1.1k} /opt/bin/openssl /opt/bin/c_rehash
            ./bootstrap
            ./configure --enable-static --prefix=/opt
            make all
            tools/gs-netcat -h
            tools/gs-netcat -g
            strip tools/gs-netcat
            mv tools/gs-netcat TEST-gs-netcat_${{ matrix.os }}-x86_64

      - name: Upload gs-netcat to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: TEST-gs-netcat_*
          overwrite: true
          file_glob: true
          tag: v${{ env.VER }}


